services:
  mariadb:
    image: mariadb:11.4
    container_name: nlab-mariadb
    profiles: ["observability"]
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "practice"
      MARIADB_DATABASE: "notification"
    volumes:
      - ../mariadb/init:/docker-entrypoint-initdb.d:ro
